package Resep;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Resb
 */
public class FrameMieAceh extends javax.swing.JFrame {


    /**
     * Creates new form FrameNasi
     */
    public FrameMieAceh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea1 = new javax.swing.JTextArea();

        setTitle("Resep Nasi Goreng");
        setBackground(new java.awt.Color(255, 255, 153));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bahan:\n150 gram daging sapi/kambing, iris bentuk batang korek api\n100 gram udang kupas\n750 ml kaldu daging atau air biasa\n150 gram kol, iris tipis\n75 gram taoge\n500 gram mie aceh (mie giling)\n2 siung bawang putih, iris tipis\n3 siung bawang merah, iris tipis\n1 buah tomat merah, potong dadu\n2 batang daun bawang, iris tipis\n2 batang seledri, iris tipis\n1 1/2 sdt cuka\n1 sdm kecap asin\n\nBumbu halus:\n4 siung bawang merah\n3 siung bawang putih\n3 buah cabai merah\n1 sdm bumbu kari bubuk\n1/2 sdt jinten, sangrai\n3 butir kapu laga\n1/2 sdt lada butiran\n2 sdt garam\n\nBahan pelengkap:\nEmping goreng\nAcar timun\n\nCara membuat:\n1. Panaskan minyak, tumis bawang putih, bawang \nmerah, dan tomat hingga harum. Masukkan daging \nkambing/sapi dan udang. Aduk sebentar.\n\n2. Tambahkan bumbu halus dan kaldu daging/air. \nTutup wajan, masak hingga mendidih kurang lebih \nselama satu sampai dua menit. Masukkan taoge, kol, \ncuka, dan kecap asin, didihkan kembali.\n\n3. Masukkan mie, daun bawang dan seledri. Tambahkan \ngaram bila perlu, aduk sampai merata. Masak hingga \nmendidih, aduk dan segera angkat. Sajikan dengan \npelengkap.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMieAceh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMieAceh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMieAceh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMieAceh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMieAceh().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
