
import Resep.FrameAyamGoreng;
import Resep.FrameBakso;
import Resep.FrameGudeg;
import Resep.FrameMieAceh;
import Resep.FrameNasi;
import Resep.FrameRendang;
import Resep.FrameSayurAsem;
import Resep.FrameSoto;
import Resep.FrameTahuTempe;
import Resep.FrameTelur;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Resb
 */
public class FrameResep extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public FrameResep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton BNasi = new javax.swing.JButton();
        javax.swing.JButton BRendang = new javax.swing.JButton();
        javax.swing.JButton BMieAceh = new javax.swing.JButton();
        javax.swing.JButton BSoto = new javax.swing.JButton();
        javax.swing.JButton BTahuTempe = new javax.swing.JButton();
        javax.swing.JButton BBakso = new javax.swing.JButton();
        javax.swing.JButton BAyamGoreng = new javax.swing.JButton();
        javax.swing.JButton BGudek = new javax.swing.JButton();
        javax.swing.JButton BSayurAsem = new javax.swing.JButton();
        javax.swing.JButton BTelur = new javax.swing.JButton();

        setTitle("Resep");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("List Resep");

        BNasi.setText("Nasi Goreng");
        BNasi.setPreferredSize(new java.awt.Dimension(100, 30));
        BNasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNasiActionPerformed(evt);
            }
        });

        BRendang.setText("Rendang");
        BRendang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRendangActionPerformed(evt);
            }
        });

        BMieAceh.setText("Mie Aceh");
        BMieAceh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMieAcehActionPerformed(evt);
            }
        });

        BSoto.setText("Soto");
        BSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSotoActionPerformed(evt);
            }
        });

        BTahuTempe.setText("Tahu Tempe Bacem");
        BTahuTempe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTahuTempeActionPerformed(evt);
            }
        });

        BBakso.setText("Bakso");
        BBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBaksoActionPerformed(evt);
            }
        });

        BAyamGoreng.setText("Ayam Goreng");
        BAyamGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAyamGorengActionPerformed(evt);
            }
        });

        BGudek.setText("Gudeg");
        BGudek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGudekActionPerformed(evt);
            }
        });

        BSayurAsem.setText("Sayur Asem");
        BSayurAsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSayurAsemActionPerformed(evt);
            }
        });

        BTelur.setText("Olahan Telur");
        BTelur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTelurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BRendang)
                    .addComponent(BMieAceh)
                    .addComponent(BSoto)
                    .addComponent(BTahuTempe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBakso)
                    .addComponent(BAyamGoreng)
                    .addComponent(BGudek)
                    .addComponent(BSayurAsem)
                    .addComponent(BTelur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BAyamGoreng, BBakso, BGudek, BMieAceh, BNasi, BRendang, BSayurAsem, BSoto, BTahuTempe, BTelur});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BRendang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BMieAceh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BSoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTahuTempe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BBakso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BAyamGoreng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BGudek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BSayurAsem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTelur)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BAyamGoreng, BBakso, BGudek, BMieAceh, BNasi, BRendang, BSayurAsem, BSoto, BTahuTempe, BTelur});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNasiActionPerformed
        // TODO add your handling code here:
        FrameNasi FrameNasi = new FrameNasi();          //* Membuat Frame Baru
        FrameNasi.setVisible(true);                   //* Menampilkan Frame Baru   
    }//GEN-LAST:event_BNasiActionPerformed

    private void BTahuTempeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTahuTempeActionPerformed
        // TODO add your handling code here:
        FrameTahuTempe FrameTahuTempe = new FrameTahuTempe();
        FrameTahuTempe.setVisible(true);
    }//GEN-LAST:event_BTahuTempeActionPerformed

    private void BRendangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRendangActionPerformed
        // TODO add your handling code here:
        FrameRendang FrameRendang = new FrameRendang();
        FrameRendang.setVisible(true);
    }//GEN-LAST:event_BRendangActionPerformed

    private void BMieAcehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMieAcehActionPerformed
        // TODO add your handling code here:
        FrameMieAceh FrameMieAceh = new FrameMieAceh();
        FrameMieAceh.setVisible(true);
    }//GEN-LAST:event_BMieAcehActionPerformed

    private void BSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSotoActionPerformed
        // TODO add your handling code here:
        FrameSoto FrameSoto = new FrameSoto();
        FrameSoto.setVisible(true);
    }//GEN-LAST:event_BSotoActionPerformed

    private void BBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBaksoActionPerformed
        // TODO add your handling code here:
        FrameBakso FrameBakso = new FrameBakso();
        FrameBakso.setVisible(true);
    }//GEN-LAST:event_BBaksoActionPerformed

    private void BAyamGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAyamGorengActionPerformed
        // TODO add your handling code here:
        FrameAyamGoreng FrameAyamGoreng = new FrameAyamGoreng();
        FrameAyamGoreng.setVisible(true);
    }//GEN-LAST:event_BAyamGorengActionPerformed

    private void BGudekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGudekActionPerformed
        // TODO add your handling code here:
        FrameGudeg FrameGudeg = new FrameGudeg();
        FrameGudeg.setVisible(true);
    }//GEN-LAST:event_BGudekActionPerformed

    private void BSayurAsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSayurAsemActionPerformed
        // TODO add your handling code here:
        FrameSayurAsem FrameSayurAsem = new FrameSayurAsem();
        FrameSayurAsem.setVisible(true);
    }//GEN-LAST:event_BSayurAsemActionPerformed

    private void BTelurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTelurActionPerformed
        // TODO add your handling code here:
        FrameTelur FrameTelur = new FrameTelur();
        FrameTelur.setVisible(true);
    }//GEN-LAST:event_BTelurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameResep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
